### ISSUE TITLE
Ascii HTML Mode

### ISSUE THREAD

**Issue by ai4teru** [LeandroBarone/python-ascii_magic#3]
When trying to use ascii_magic.Modes.HTML, this is generated instead.

Code: 
import ascii_magic
output = ascii_magic.from_image_file("dogedemo.png", mode=ascii_magic.Modes.HTML)
ascii_magic.to_terminal(output)

Result:
![image](https://user-images.githubusercontent.com/79354962/124368395-86dd3500-dc15-11eb-895c-a75e70f8a4b5.png)

**Comment by LeandroBarone** [comment]
Keep in mind that you're generating HTML code in the second line and outputting it to the terminal in the third line. You should output that HTML code to an HTML file.

Maybe the example on the readme file was not clear enough? If so, I'm updating it.
